# Generated by Django 4.0.5 on 2022-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_position', models.CharField(choices=[('AP', 'аспирант'), ('AS', 'ассистент'), ('VN', 'ведущий научный сотрудник'), ('GN', 'главный научный сотрудник'), ('DO', 'докторант'), ('DC', 'доцент'), ('MN', 'младший научный сотрудник'), ('NS', 'научный сотрудник'), ('PR', 'преподаватель'), ('PF', 'профессор'), ('SP', 'старший преподаватель'), ('ST', 'стажёр'), ('SN', 'старший научный сотрудник')], default='PR', max_length=2)),
                ('teacher_education', models.CharField(max_length=10)),
                ('teacher_photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
