# Generated by Django 4.0.5 on 2022-07-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
    ]
