# Generated by Django 4.0.5 on 2022-07-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_teacher_teacher_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('TE', 'Преподавательская'), ('LE', 'Учебная')], default='TE', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.ForeignKey(limit_choices_to={'room_type': 'PR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
    ]
