# Generated by Django 4.0.5 on 2022-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_room_room_type_alter_teacher_teacher_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
