# Generated by Django 4.0.5 on 2022-07-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.OneToOneField(limit_choices_to={'room_type': 'PR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('LE', 'Лекция'), ('PR', 'Практика')], default='PR', max_length=2)),
                ('lesson_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.discipline')),
                ('lesson_groups', models.ManyToManyField(to='info.group')),
                ('lesson_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.teacher')),
            ],
        ),
    ]
