# Generated by Django 4.0.5 on 2022-07-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_discipline_group_alter_teacher_teacher_room_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.ForeignKey(limit_choices_to={'room_type': 'PR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
    ]
