# Generated by Django 4.0.6 on 2022-07-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_teacher_teacher_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'дисциплина', 'verbose_name_plural': 'дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'занятие', 'verbose_name_plural': 'занятия'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'аудитория', 'verbose_name_plural': 'аудитории'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'преподаватель', 'verbose_name_plural': 'преподаватели'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_hours_a_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_additional_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('ЛК', 'Лекция'), ('ПР', 'Практика'), ('КР', 'Контрольная работа'), ('ЭК', 'Экзамен'), ('КС', 'Консультация')], default='ПР', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_position',
            field=models.CharField(choices=[('AS', 'ассистент'), ('DC', 'доцент'), ('PR', 'преподаватель'), ('PF', 'профессор'), ('SP', 'старший преподаватель'), ('ST', 'стажёр')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.ForeignKey(limit_choices_to={'room_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
    ]
