# Generated by Django 4.0.6 on 2022-07-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_discipline_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.OneToOneField(limit_choices_to={'room_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room'),
        ),
    ]
