# Generated by Django 4.0.6 on 2022-07-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_teacher_teacher_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_hours_a_week',
        ),
    ]
