# Generated by Django 4.0.6 on 2022-07-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_teacher_teacher_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_groups',
        ),
        migrations.AddField(
            model_name='discipline',
            name='discipline_groups',
            field=models.ManyToManyField(to='info.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('ЛК', 'Лекции'), ('ПР', 'Практики')], default='ПР', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_room',
            field=models.ForeignKey(limit_choices_to={'room_type': 'TE'}, on_delete=django.db.models.deletion.RESTRICT, to='info.room'),
        ),
    ]
