# Generated by Django 4.0.6 on 2022-07-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_lesson_lesson_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='discipline_groups',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='discipline_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_discipline',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_additional_work',
            new_name='additional_work',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_room',
            new_name='room',
        ),
    ]
