# Generated by Django 4.0.6 on 2022-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_lesson_lesson_type_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
