# Generated by Django 4.0.6 on 2022-07-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'учёная степень',
                'verbose_name_plural': 'учёные степени',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.education'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.position'),
        ),
    ]
