# Generated by Django 4.0.6 on 2022-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_education_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
