# Generated by Django 4.0.6 on 2022-07-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_education_field_alter_education_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.education'),
        ),
    ]
