# Generated by Django 4.0.6 on 2022-07-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_rename_name_education_level_alter_teacher_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(max_length=50, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=15, verbose_name='степень'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.discipline', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('ЛК', 'лекции'), ('ПР', 'практики')], default='ПР', max_length=2, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.teacher', verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('TE', 'Преподавательская'), ('LE', 'Учебная')], default='TE', max_length=2, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_work',
            field=models.TextField(blank=True, default='', verbose_name='дополнительная деятельность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.education', verbose_name='учёная степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.position', verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.ForeignKey(limit_choices_to={'room_type': 'TE'}, on_delete=django.db.models.deletion.RESTRICT, to='info.room', verbose_name='аудитория'),
        ),
    ]
