# Generated by Django 4.0.6 on 2022-07-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_alter_discipline_name_alter_education_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='info.teacher', verbose_name='преподаватель'),
        ),
    ]
