# Generated by Django 4.0.6 on 2022-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='info.teacher', verbose_name='преподаватель'),
        ),
    ]
