# Generated by Django 4.0.6 on 2022-07-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'room_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.room', verbose_name='аудитория'),
        ),
    ]
