# Generated by Django 4.0.6 on 2022-09-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_alter_teacher_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='вид')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('TE', 'Преподавательская'), ('LE', 'Учебная'), ('AD', 'Администрация'), ('OF', 'Служебное помещение')], default='TE', max_length=2, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.lessontype', verbose_name='вид занятия'),
        ),
    ]
