# Generated by Django 4.0.6 on 2022-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_lessontype_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'вид занятия', 'verbose_name_plural': 'виды занятий'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='info.lesson', verbose_name='занятия'),
        ),
    ]
